
package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;


public class RegistrationView1 extends javax.swing.JFrame {


    public RegistrationView1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        passPsf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmPsf = new javax.swing.JPasswordField();
        confirmPassshowbtn = new javax.swing.JButton();
        passShowbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        alreadyLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTxt1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirm Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        jLabel3.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 20));
        jPanel1.add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 334, 30));
        jPanel1.add(passPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 334, 30));

        jLabel4.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 100, 20));
        jPanel1.add(confirmPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 334, 30));

        confirmPassshowbtn.setText("Show");
        jPanel1.add(confirmPassshowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        passShowbtn.setText("Show");
        jPanel1.add(passShowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Register");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 340, -1));

        alreadyLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        alreadyLbl.setForeground(new java.awt.Color(51, 51, 51));
        alreadyLbl.setText("Already Have An Account?");
        jPanel1.add(alreadyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("bookmyvenue");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nepal’s no.1 booking platform");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 60, 200, -1));
        jPanel1.add(emailTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 334, 30));

        jLabel7.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel alreadyLbl;
    private javax.swing.JButton confirmPassshowbtn;
    private javax.swing.JPasswordField confirmPsf;
    private javax.swing.JTextField emailTxt1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passPsf;
    private javax.swing.JButton passShowbtn;
    // End of variables declaration//GEN-END:variables

                 

    
    public void RegisterUserListener(ActionListener listener)
    {
        this.jButton3.addActionListener(listener);
    }
    
    public void LoginNavigate(MouseListener listener)
    {
        this.alreadyLbl.addMouseListener(listener);
    }
    
    public void showPasswordListener(ActionListener listener)
    {
        this.getPassShowbtn().addActionListener(listener);
    }
    
    public void showConfirmPasswordListener(ActionListener listener)
    {
        this.getConfirmPassshowbtn().addActionListener(listener);
    }

    /**
     * @return the confirmPsf
     */
    public javax.swing.JPasswordField getConfirmPsf() {
        return confirmPsf;
    }

    /**
     * @param confirmPsf the confirmPsf to set
     */
    public void setConfirmPsf(javax.swing.JPasswordField confirmPsf) {
        this.confirmPsf = confirmPsf;
    }

    /**
     * @return the emailTxt
     */
    public javax.swing.JTextField getEmailTxt() {
        return NameTxt;
    }

    /**
     * @param emailTxt the emailTxt to set
     */
    public void setEmailTxt(javax.swing.JTextField emailTxt) {
        this.NameTxt = emailTxt;
    }

    /**
     * @return the passPsf
     */
    public javax.swing.JPasswordField getPassPsf() {
        return passPsf;
    }

    /**
     * @param passPsf the passPsf to set
     */
    public void setPassPsf(javax.swing.JPasswordField passPsf) {
        this.passPsf = passPsf;
    }

    /**
     * @return the confirmPassshowbtn
     */
    public javax.swing.JButton getConfirmPassshowbtn() {
        return confirmPassshowbtn;
    }

    /**
     * @param confirmPassshowbtn the confirmPassshowbtn to set
     */
    public void setConfirmPassshowbtn(javax.swing.JButton confirmPassshowbtn) {
        this.confirmPassshowbtn = confirmPassshowbtn;
    }

    /**
     * @return the passShowbtn
     */
    public javax.swing.JButton getPassShowbtn() {
        return passShowbtn;
    }

    /**
     * @param passShowbtn the passShowbtn to set
     */
    public void setPassShowbtn(javax.swing.JButton passShowbtn) {
        this.passShowbtn = passShowbtn;
    }
}

