package javaapplication6.view;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication6.controller.FAQController;

/**
 *
 * @author Dell
 */
public class AdminDashboardView extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public AdminDashboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        viewBookingButton1 = new javax.swing.JButton();
        registervenue = new javax.swing.JButton();
        change = new javax.swing.JButton();
        updatedetails = new javax.swing.JButton();
        updatedetails1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Settings");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 6, 66, -1));

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.setBorderPainted(false);
        logout.setOpaque(true);
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 341, 172, 31));

        viewBookingButton1.setBackground(new java.awt.Color(0, 0, 0));
        viewBookingButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewBookingButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewBookingButton1.setText("View Booking Request");
        viewBookingButton1.setBorderPainted(false);
        viewBookingButton1.setOpaque(true);
        jPanel2.add(viewBookingButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 36));

        registervenue.setBackground(new java.awt.Color(51, 255, 0));
        registervenue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registervenue.setText("Register Venue");
        registervenue.setBorderPainted(false);
        registervenue.setOpaque(true);
        jPanel2.add(registervenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 36));

        change.setBackground(new java.awt.Color(0, 0, 0));
        change.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setText("Change Password");
        change.setBorderPainted(false);
        change.setOpaque(true);
        jPanel2.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 172, 33));

        updatedetails.setBackground(new java.awt.Color(0, 0, 0));
        updatedetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatedetails.setForeground(new java.awt.Color(255, 255, 255));
        updatedetails.setText("Add Venue");
        updatedetails.setBorderPainted(false);
        updatedetails.setFocusPainted(false);
        updatedetails.setOpaque(true);
        jPanel2.add(updatedetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 172, 35));

        updatedetails1.setBackground(new java.awt.Color(0, 0, 0));
        updatedetails1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatedetails1.setForeground(new java.awt.Color(255, 255, 255));
        updatedetails1.setText("Update Venue Details");
        updatedetails1.setBorderPainted(false);
        updatedetails1.setFocusPainted(false);
        updatedetails1.setOpaque(true);
        jPanel2.add(updatedetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 172, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton registervenue;
    private javax.swing.JButton updatedetails;
    private javax.swing.JButton updatedetails1;
    private javax.swing.JButton viewBookingButton1;
    // End of variables declaration//GEN-END:variables

    public void RegisterUserListener(ActionListener listener)
    {
        this.viewBookingButton1.addActionListener(listener);
    }
    public void RegisteVenueUserListener(ActionListener listener)
    {
        this.registervenue.addActionListener(listener);
    }
    public void UpdeteDetailsUserListener(ActionListener listener)
    {
        this.updatedetails1.addActionListener(listener);
    }
    public void ChangepassUserListener(ActionListener listener)
    {
        this.change.addActionListener(listener);
    }
    public void LogOutUserListener(ActionListener listener)
    {
        this.logout.addActionListener(listener);
    }
    
}
