package javaapplication6.view;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Dell
 */
public class BookingDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form MyBookings
     */
    public BookingDetailsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backprofile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        venueName = new javax.swing.JLabel();
        rejectbooking = new javax.swing.JButton();
        venueLocation = new javax.swing.JLabel();
        guestNumber = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        adminEmail = new javax.swing.JLabel();
        approvebooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backprofile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backprofile.setText("Back to Profile");
        getContentPane().add(backprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 22, 94, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("My Bookings");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 90, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        venueName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName.setForeground(new java.awt.Color(255, 255, 255));
        venueName.setText("Demo venue name");

        rejectbooking.setBackground(new java.awt.Color(255, 51, 51));
        rejectbooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rejectbooking.setText("Reject Booking");
        rejectbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectbookingActionPerformed(evt);
            }
        });

        venueLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueLocation.setForeground(new java.awt.Color(255, 255, 255));
        venueLocation.setText("Demo venue location");

        guestNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guestNumber.setForeground(new java.awt.Color(255, 255, 255));
        guestNumber.setText("Estimated guest number");

        price.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Demo price");

        adminEmail.setBackground(new java.awt.Color(255, 255, 255));
        adminEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminEmail.setForeground(new java.awt.Color(255, 255, 255));
        adminEmail.setText("demo contact email");

        approvebooking.setBackground(new java.awt.Color(51, 204, 0));
        approvebooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        approvebooking.setText("Approve Booking");
        approvebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvebookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(venueName)
                            .addComponent(venueLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guestNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(approvebooking)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rejectbooking)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venueName)
                    .addComponent(price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(venueLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guestNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rejectbooking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approvebooking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rejectbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectbookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejectbookingActionPerformed

    private void approvebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvebookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_approvebookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminEmail;
    private javax.swing.JButton approvebooking;
    private javax.swing.JLabel backprofile;
    private javax.swing.JLabel guestNumber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel price;
    private javax.swing.JButton rejectbooking;
    private javax.swing.JLabel venueLocation;
    private javax.swing.JLabel venueName;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the adminEmail
     */
    public javax.swing.JLabel getAdminEmail() {
        return adminEmail;
    }

    /**
     * @param adminEmail the adminEmail to set
     */
    public void setAdminEmail(javax.swing.JLabel adminEmail) {
        this.adminEmail = adminEmail;
    }

    /**
     * @return the adminPhone
     */
   
    /**
     * @return the cancelBooking
     */
    public javax.swing.JButton getCancelBooking() {
        return rejectbooking;
    }

    /**
     * @param cancelBooking the cancelBooking to set
     */
    public void setCancelBooking(javax.swing.JButton cancelBooking) {
        this.rejectbooking = cancelBooking;
    }

    /**
     * @return the guestNumber
     */
    public javax.swing.JLabel getGuestNumber() {
        return guestNumber;
    }

    /**
     * @param guestNumber the guestNumber to set
     */
    public void setGuestNumber(javax.swing.JLabel guestNumber) {
        this.guestNumber = guestNumber;
    }

    /**
     * @return the venueLocation
     */
    public javax.swing.JLabel getVenueLocation() {
        return venueLocation;
    }

    /**
     * @param venueLocation the venueLocation to set
     */
    public void setVenueLocation(javax.swing.JLabel venueLocation) {
        this.venueLocation = venueLocation;
    }

    /**
     * @return the venueName
     */
    public javax.swing.JLabel getVenueName() {
        return venueName;
    }

    /**
     * @param venueName the venueName to set
     */
    public void setVenueName(javax.swing.JLabel venueName) {
        this.venueName = venueName;
    }


    
    public void backListener(MouseListener listener)
    {
        this.backprofile.addMouseListener(listener);
    }

    /**
     * @return the price
     */
    public javax.swing.JLabel getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(javax.swing.JLabel price) {
        this.price = price;
    }
        
    public void RejectBookingListener(ActionListener listener){
        
        this.rejectbooking.addActionListener(listener);
    }
    public void ApproveBookingListener(ActionListener listener){
        
    this.approvebooking.addActionListener(listener);
    }
    




}
