/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Yuri Maharjan
 */
public class BookVenue extends javax.swing.JFrame {

    /**
     * Creates new form BookVenue
     */
    public BookVenue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        guest = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bkovenue = new javax.swing.JButton();
        uscontact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 19, 70, 60));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Profile");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        email.setEditable(false);
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 190, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Email:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 20));

        name.setEditable(false);
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Venue Name:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Contact:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, 20));

        contact.setEditable(false);
        jPanel3.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 190, 20));

        date.setEditable(false);
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 190, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Date:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Time:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 20));

        time.setEditable(false);
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 190, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Event Type:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 20));

        type.setEditable(false);
        jPanel3.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 20));

        guest.setEditable(false);
        jPanel3.add(guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 190, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Estimated Number of Guests:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 20));

        jLabel8.setText("Menue");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel8)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, 200));

        bkovenue.setText("Book Venue");
        jPanel3.add(bkovenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        uscontact.setText("Contact us");
        jPanel3.add(uscontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 620, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkovenue;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JTextField guest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField time;
    private javax.swing.JTextField type;
    private javax.swing.JButton uscontact;
    // End of variables declaration//GEN-END:variables
       public void BookVenueActionListener(ActionListener listener)
    {
        this.bkovenue.addActionListener(listener);
    }
       public void ContactusActionListener(ActionListener listener)
    {
        this.uscontact.addActionListener(listener);
    }

    /**
     * @return the contact
     */
    public javax.swing.JTextField getContact() {
        return contact;
    }

    /**
     * @param contact the contact to set
     */
    public void setContact(javax.swing.JTextField contact) {
        this.contact = contact;
    }

    /**
     * @return the date
     */
    public javax.swing.JTextField getDate() {
        return date;
    }

    /**
     * @param date the date to set
     */
    public void setDate(javax.swing.JTextField date) {
        this.date = date;
    }

    /**
     * @return the email
     */
    public javax.swing.JTextField getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(javax.swing.JTextField email) {
        this.email = email;
    }

    /**
     * @return the guest
     */
    public javax.swing.JTextField getGuest() {
        return guest;
    }

    /**
     * @param guest the guest to set
     */
    public void setGuest(javax.swing.JTextField guest) {
        this.guest = guest;
    }



    /**
     * @param name the name to set
     */
    public void setName(javax.swing.JTextField name) {
        this.name = name;
    }

    /**
     * @return the time
     */
    public javax.swing.JTextField getTime() {
        return time;
    }

    /**
     * @param time the time to set
     */
    public void setTime(javax.swing.JTextField time) {
        this.time = time;
    }


    /**
     * @param type the type to set
     */
    public void setType(javax.swing.JTextField type) {
        this.type = type;
    }

   

}
