/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author ishan-college
 */
public class EnterOTPView extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassView
     */
    public EnterOTPView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        loginLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        otpTxt = new javax.swing.JTextField();
        verifyBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(735, 569));
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLbl.setForeground(new java.awt.Color(102, 204, 0));
        loginLbl.setText("Login");
        jPanel6.add(loginLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 50, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Forgot Password?");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 240, 53));

        jLabel3.setText("Enter the OTP to Verify");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 240, -1));
        jPanel6.add(otpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 246, -1));

        verifyBtn.setBackground(new java.awt.Color(0, 0, 0));
        verifyBtn.setForeground(new java.awt.Color(255, 255, 255));
        verifyBtn.setText("Verify");
        verifyBtn.setBorderPainted(false);
        verifyBtn.setOpaque(true);
        jPanel6.add(verifyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, -1));

        jLabel4.setText("Enter OTP");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, 20));

        jLabel5.setText("Remember password?");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 148, -1));

        getContentPane().add(jPanel6);
        jPanel6.setBounds(120, 90, 500, 340);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterOTPView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JTextField otpTxt;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
    
    
    public void VerifyActionListener(ActionListener listener)
    {
        this.verifyBtn.addActionListener(listener);
    }
    public void ForgetActionListener(MouseListener listener)
    {
        this.loginLbl.addMouseListener(listener);
    }

    /**
     * @return the otpTxt
     */
    public javax.swing.JTextField getOtpTxt() {
        return otpTxt;
    }

    /**
     * @param otpTxt the otpTxt to set
     */
    public void setOtpTxt(javax.swing.JTextField otpTxt) {
        this.otpTxt = otpTxt;
    }
    
}