/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package javaapplication6.view;

import java.awt.event.ActionListener;

/**
 *
 * @author ishan-college
 */
public class InquiryView extends javax.swing.JFrame {

    /** Creates new form InquiryView */
    public InquiryView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageTxt = new javax.swing.JTextArea();
        SendBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contact us");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(470, 120, 165, 30);

        EmailTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        EmailTxt.setForeground(new java.awt.Color(204, 204, 204));
        EmailTxt.setText("Enter your email");
        jPanel2.add(EmailTxt);
        EmailTxt.setBounds(550, 230, 240, 40);

        MessageTxt.setColumns(20);
        MessageTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        MessageTxt.setForeground(new java.awt.Color(204, 204, 204));
        MessageTxt.setRows(5);
        MessageTxt.setText("Enter your message");
        MessageTxt.setToolTipText("");
        jScrollPane1.setViewportView(MessageTxt);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(310, 300, 480, 180);

        SendBtn.setBackground(new java.awt.Color(0, 204, 51));
        SendBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SendBtn.setForeground(new java.awt.Color(255, 255, 255));
        SendBtn.setText("SEND");
        jPanel2.add(SendBtn);
        SendBtn.setBounds(310, 510, 480, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Got any questions or suggestions? Fill out this form to reach out.");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(310, 170, 480, 24);

        NameTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        NameTxt.setForeground(new java.awt.Color(204, 204, 204));
        NameTxt.setText("Enter your name");
        jPanel2.add(NameTxt);
        NameTxt.setBounds(310, 230, 210, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InquiryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InquiryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InquiryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InquiryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InquiryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JTextArea MessageTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JButton SendBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the EmailTxt
     */
    public javax.swing.JTextField getEmailTxt() {
        return EmailTxt;
    }

    /**
     * @param EmailTxt the EmailTxt to set
     */
    public void setEmailTxt(javax.swing.JTextField EmailTxt) {
        this.EmailTxt = EmailTxt;
    }

    /**
     * @return the MessageTxt
     */
    public javax.swing.JTextArea getMessageTxt() {
        return MessageTxt;
    }

    /**
     * @param MessageTxt the MessageTxt to set
     */
    public void setMessageTxt(javax.swing.JTextArea MessageTxt) {
        this.MessageTxt = MessageTxt;
    }

    /**
     * @return the NameTxt
     */
    public javax.swing.JTextField getNameTxt() {
        return NameTxt;
    }

    /**
     * @param NameTxt the NameTxt to set
     */
    public void setNameTxt(javax.swing.JTextField NameTxt) {
        this.NameTxt = NameTxt;
    }

    public void SendListener(ActionListener listener)
    {
        this.SendBtn.addActionListener(listener);
    }
}
