package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ishan-college
 */
public class LoginView extends javax.swing.JFrame {
    
    

    /**
     * Creates new form NewJFrame
     */
    public LoginView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passPsf = new javax.swing.JPasswordField();
        showBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        signupLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        forgetLbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        entryViewlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(732, 569));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passPsf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(passPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 280, 50));

        showBtn.setBackground(new java.awt.Color(51, 255, 0));
        showBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showBtn.setText("Show");
        showBtn.setBorderPainted(false);
        showBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showBtnMouseClicked(evt);
            }
        });
        jPanel1.add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 90, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 30));

        signupLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signupLbl.setForeground(new java.awt.Color(102, 204, 0));
        signupLbl.setText("Sign Up");
        signupLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(signupLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 60, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User Login Page");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        emailTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 280, 50));

        forgetLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgetLbl.setForeground(new java.awt.Color(255, 0, 0));
        forgetLbl.setText("Forgot Password ?");
        forgetLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetLblMouseClicked(evt);
            }
        });
        jPanel1.add(forgetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setToolTipText("");
        loginBtn.setBorderPainted(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setOpaque(true);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 280, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Don't have an account?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 170, 20));

        jPanel3.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6.Image/bookmyvenue.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 0, 110, 60);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 60));

        entryViewlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entryViewlabel.setText("Back to Entry View");
        entryViewlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(entryViewlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showBtnMouseClicked

    private void forgetLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetLblMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel entryViewlabel;
    private javax.swing.JLabel forgetLbl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passPsf;
    private javax.swing.JButton showBtn;
    private javax.swing.JLabel signupLbl;
    // End of variables declaration//GEN-END:variables

    public void ShowActionListener(ActionListener listener)
    {
        this.getShowBtn().addActionListener(listener);
    }
    
    public void LoginActionListener(ActionListener listener)
    {
        this.loginBtn.addActionListener(listener);
    }
    
    public void ForgetActionListener(MouseListener listener)
    {
        this.forgetLbl.addMouseListener(listener);
    }
    public void EntryViewListener(MouseListener listener)
    {
        this.entryViewlabel.addMouseListener(listener);
    }
    
    public void SignupActionListener(MouseListener listener)
    {
        this.signupLbl.addMouseListener(listener);
    }

    /**
     * @return the emailTxt
     */
    public javax.swing.JTextField getEmailTxt() {
        return emailTxt;
    }

    /**
     * @param emailTxt the emailTxt to set
     */
    public void setEmailTxt(javax.swing.JTextField emailTxt) {
        this.emailTxt = emailTxt;
    }

    /**
     * @return the passPsf
     */
    public javax.swing.JPasswordField getPassPsf() {
        return passPsf;
    }

    /**
     * @param passPsf the passPsf to set
     */
    public void setPassPsf(javax.swing.JPasswordField passPsf) {
        this.passPsf = passPsf;
    }

    /**
     * @return the showBtn
     */
    public javax.swing.JButton getShowBtn() {
        return showBtn;
    }

    /**
     * @param showBtn the showBtn to set
     */
    public void setShowBtn(javax.swing.JButton showBtn) {
        this.showBtn = showBtn;
    }
    
    

    
    
}
