package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ishan-college
 */
public class LoginView extends javax.swing.JFrame {
    
    

    /**
     * Creates new form NewJFrame
     */
    public LoginView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passPsf = new javax.swing.JPasswordField();
        showBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        signupLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        forgetLbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(732, 569));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(passPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 246, -1));

        showBtn.setText("Show");
        showBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showBtnMouseClicked(evt);
            }
        });
        jPanel1.add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 70, -1));

        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        signupLbl.setForeground(new java.awt.Color(102, 204, 0));
        signupLbl.setText("Sign Up");
        signupLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLblMouseClicked(evt);
            }
        });
        jPanel1.add(signupLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel5.setText("bookmyvenue");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 240, 53));
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 246, -1));

        forgetLbl.setForeground(new java.awt.Color(255, 0, 0));
        forgetLbl.setText("Forget Password");
        forgetLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetLblMouseClicked(evt);
            }
        });
        jPanel1.add(forgetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 250, -1));

        jLabel9.setText("Nepal's no.1 booking platform");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 220, -1));

        jLabel11.setText("Don't have an account?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 148, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 530, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLblMouseClicked
        // TODO add your handling code here:
//        new RegistrationView().setVisible(true);
//        dispose();
        
    }//GEN-LAST:event_signupLblMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMouseClicked

    private void showBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showBtnMouseClicked

    private void forgetLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel forgetLbl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passPsf;
    private javax.swing.JButton showBtn;
    private javax.swing.JLabel signupLbl;
    // End of variables declaration//GEN-END:variables

    public void ShowActionListener(ActionListener listener)
    {
        this.getShowBtn().addActionListener(listener);
    }
    
    public void LoginActionListener(ActionListener listener)
    {
        this.loginBtn.addActionListener(listener);
    }
    
    public void ForgetActionListener(MouseListener listener)
    {
        this.forgetLbl.addMouseListener(listener);
    }
    
    public void SignupActionListener(MouseListener listener)
    {
        this.addMouseListener(listener);
    }

    /**
     * @return the emailTxt
     */
    public javax.swing.JTextField getEmailTxt() {
        return emailTxt;
    }

    /**
     * @param emailTxt the emailTxt to set
     */
    public void setEmailTxt(javax.swing.JTextField emailTxt) {
        this.emailTxt = emailTxt;
    }

    /**
     * @return the passPsf
     */
    public javax.swing.JPasswordField getPassPsf() {
        return passPsf;
    }

    /**
     * @param passPsf the passPsf to set
     */
    public void setPassPsf(javax.swing.JPasswordField passPsf) {
        this.passPsf = passPsf;
    }

    /**
     * @return the showBtn
     */
    public javax.swing.JButton getShowBtn() {
        return showBtn;
    }

    /**
     * @param showBtn the showBtn to set
     */
    public void setShowBtn(javax.swing.JButton showBtn) {
        this.showBtn = showBtn;
    }
    
    

    
    
}
