/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Dell
 */
public class MyBookings extends javax.swing.JFrame {

    /**
     * Creates new form MyBookings
     */
    public MyBookings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        venueName = new javax.swing.JLabel();
        cancelBooking = new javax.swing.JButton();
        venueLocation = new javax.swing.JLabel();
        guestNumber = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        adminEmail = new javax.swing.JLabel();
        adminPhone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backprofile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        venueName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName.setForeground(new java.awt.Color(185, 250, 46));
        venueName.setText("Demo venue name");

        cancelBooking.setBackground(new java.awt.Color(255, 51, 51));
        cancelBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBooking.setForeground(new java.awt.Color(255, 255, 255));
        cancelBooking.setText("Cancel Booking");
        cancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingActionPerformed(evt);
            }
        });

        venueLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueLocation.setForeground(new java.awt.Color(185, 250, 46));
        venueLocation.setText("Demo venue location");

        guestNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guestNumber.setForeground(new java.awt.Color(185, 250, 46));
        guestNumber.setText("Estimated guest number");

        price.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price.setForeground(new java.awt.Color(185, 250, 46));
        price.setText("Demo price");

        adminEmail.setBackground(new java.awt.Color(255, 255, 255));
        adminEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminEmail.setForeground(new java.awt.Color(185, 250, 46));
        adminEmail.setText("demo contact email");

        adminPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminPhone.setForeground(new java.awt.Color(185, 250, 46));
        adminPhone.setText("demo contact phone number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(adminPhone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 693, Short.MAX_VALUE)
                                .addComponent(cancelBooking))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(venueLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guestNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(venueName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 788, Short.MAX_VALUE)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venueName)
                    .addComponent(price))
                .addGap(18, 18, 18)
                .addComponent(venueLocation)
                .addGap(18, 18, 18)
                .addComponent(guestNumber)
                .addGap(18, 18, 18)
                .addComponent(adminEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminPhone))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(185, 250, 46));
        jLabel2.setText("My Bookings");

        backprofile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backprofile.setForeground(new java.awt.Color(185, 250, 46));
        backprofile.setText("Back to Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(backprofile)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addContainerGap(606, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminEmail;
    private javax.swing.JLabel adminPhone;
    private javax.swing.JLabel backprofile;
    private javax.swing.JButton cancelBooking;
    private javax.swing.JLabel guestNumber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel price;
    private javax.swing.JLabel venueLocation;
    private javax.swing.JLabel venueName;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the adminEmail
     */
    public javax.swing.JLabel getAdminEmail() {
        return adminEmail;
    }

    /**
     * @param adminEmail the adminEmail to set
     */
    public void setAdminEmail(javax.swing.JLabel adminEmail) {
        this.adminEmail = adminEmail;
    }

    /**
     * @return the adminPhone
     */
    public javax.swing.JLabel getAdminPhone() {
        return adminPhone;
    }

    /**
     * @param adminPhone the adminPhone to set
     */
    public void setAdminPhone(javax.swing.JLabel adminPhone) {
        this.adminPhone = adminPhone;
    }

    /**
     * @return the cancelBooking
     */
    public javax.swing.JButton getCancelBooking() {
        return cancelBooking;
    }

    /**
     * @param cancelBooking the cancelBooking to set
     */
    public void setCancelBooking(javax.swing.JButton cancelBooking) {
        this.cancelBooking = cancelBooking;
    }

    /**
     * @return the guestNumber
     */
    public javax.swing.JLabel getGuestNumber() {
        return guestNumber;
    }

    /**
     * @param guestNumber the guestNumber to set
     */
    public void setGuestNumber(javax.swing.JLabel guestNumber) {
        this.guestNumber = guestNumber;
    }

    /**
     * @return the venueLocation
     */
    public javax.swing.JLabel getVenueLocation() {
        return venueLocation;
    }

    /**
     * @param venueLocation the venueLocation to set
     */
    public void setVenueLocation(javax.swing.JLabel venueLocation) {
        this.venueLocation = venueLocation;
    }

    /**
     * @return the venueName
     */
    public javax.swing.JLabel getVenueName() {
        return venueName;
    }

    /**
     * @param venueName the venueName to set
     */
    public void setVenueName(javax.swing.JLabel venueName) {
        this.venueName = venueName;
    }
    public void cancelBookingListener(ActionListener listener){
        
        this.cancelBooking.addActionListener(listener);
    }

    
    public void backListener(MouseListener listener)
    {
        this.backprofile.addMouseListener(listener);
    }

    /**
     * @return the price
     */
    public javax.swing.JLabel getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(javax.swing.JLabel price) {
        this.price = price;
    }
    
    




}
