/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Dell
 */
public class MyBookings extends javax.swing.JFrame {

    /**
     * Creates new form MyBookings
     */
    public MyBookings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        venueName = new javax.swing.JLabel();
        cancelBooking = new javax.swing.JButton();
        venueLocation = new javax.swing.JLabel();
        guestNumber = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        adminEmail = new javax.swing.JLabel();
        adminPhone = new javax.swing.JLabel();
        venueName1 = new javax.swing.JLabel();
        venueName2 = new javax.swing.JLabel();
        venueName3 = new javax.swing.JLabel();
        venueName4 = new javax.swing.JLabel();
        venueName5 = new javax.swing.JLabel();
        venueName6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backprofile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        venueName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName.setForeground(new java.awt.Color(185, 250, 46));
        venueName.setText("Demo venue name");

        cancelBooking.setBackground(new java.awt.Color(255, 51, 51));
        cancelBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBooking.setForeground(new java.awt.Color(255, 255, 255));
        cancelBooking.setText("Cancel Booking");
        cancelBooking.setBorderPainted(false);
        cancelBooking.setOpaque(true);
        cancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingActionPerformed(evt);
            }
        });

        venueLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueLocation.setForeground(new java.awt.Color(185, 250, 46));
        venueLocation.setText("Demo venue location");

        guestNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guestNumber.setForeground(new java.awt.Color(185, 250, 46));
        guestNumber.setText("Estimated guest number");

        price.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price.setForeground(new java.awt.Color(185, 250, 46));
        price.setText("Demo price");

        adminEmail.setBackground(new java.awt.Color(255, 255, 255));
        adminEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminEmail.setForeground(new java.awt.Color(185, 250, 46));
        adminEmail.setText("demo contact email");

        adminPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminPhone.setForeground(new java.awt.Color(185, 250, 46));
        adminPhone.setText("demo contact phone number");

        venueName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName1.setForeground(new java.awt.Color(51, 255, 255));
        venueName1.setText("Venue Name:");

        venueName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName2.setForeground(new java.awt.Color(51, 255, 255));
        venueName2.setText("Venue Location:");

        venueName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName3.setForeground(new java.awt.Color(51, 255, 255));
        venueName3.setText("No. of Guests:");

        venueName4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName4.setForeground(new java.awt.Color(51, 255, 255));
        venueName4.setText("Contact Email:");

        venueName5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName5.setForeground(new java.awt.Color(51, 255, 255));
        venueName5.setText("Contact No:");

        venueName6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venueName6.setForeground(new java.awt.Color(51, 255, 255));
        venueName6.setText("Estimated Price:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(venueName1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(venueName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(venueName6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
                            .addComponent(cancelBooking)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(venueName5)
                                .addGap(18, 18, 18)
                                .addComponent(adminPhone))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(venueName4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(venueName3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guestNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(venueName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(venueLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(555, 555, 555)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price)
                            .addComponent(venueName6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(venueName)
                            .addComponent(venueName1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venueLocation)
                    .addComponent(venueName2))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestNumber)
                    .addComponent(venueName3))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEmail)
                    .addComponent(venueName4))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPhone)
                    .addComponent(venueName5))
                .addGap(86, 86, 86)
                .addComponent(cancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("My Bookings");

        backprofile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backprofile.setText("Back to Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(backprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(450, 450, 450))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(backprofile)
                .addGap(139, 139, 139)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminEmail;
    private javax.swing.JLabel adminPhone;
    private javax.swing.JLabel backprofile;
    private javax.swing.JButton cancelBooking;
    private javax.swing.JLabel guestNumber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel price;
    private javax.swing.JLabel venueLocation;
    private javax.swing.JLabel venueName;
    private javax.swing.JLabel venueName1;
    private javax.swing.JLabel venueName2;
    private javax.swing.JLabel venueName3;
    private javax.swing.JLabel venueName4;
    private javax.swing.JLabel venueName5;
    private javax.swing.JLabel venueName6;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the adminEmail
     */
    public javax.swing.JLabel getAdminEmail() {
        return adminEmail;
    }

    /**
     * @param adminEmail the adminEmail to set
     */
    public void setAdminEmail(javax.swing.JLabel adminEmail) {
        this.adminEmail = adminEmail;
    }

    /**
     * @return the adminPhone
     */
    public javax.swing.JLabel getAdminPhone() {
        return adminPhone;
    }

    /**
     * @param adminPhone the adminPhone to set
     */
    public void setAdminPhone(javax.swing.JLabel adminPhone) {
        this.adminPhone = adminPhone;
    }

    /**
     * @return the cancelBooking
     */
    public javax.swing.JButton getCancelBooking() {
        return cancelBooking;
    }

    /**
     * @param cancelBooking the cancelBooking to set
     */
    public void setCancelBooking(javax.swing.JButton cancelBooking) {
        this.cancelBooking = cancelBooking;
    }

    /**
     * @return the guestNumber
     */
    public javax.swing.JLabel getGuestNumber() {
        return guestNumber;
    }

    /**
     * @param guestNumber the guestNumber to set
     */
    public void setGuestNumber(javax.swing.JLabel guestNumber) {
        this.guestNumber = guestNumber;
    }

    /**
     * @return the venueLocation
     */
    public javax.swing.JLabel getVenueLocation() {
        return venueLocation;
    }

    /**
     * @param venueLocation the venueLocation to set
     */
    public void setVenueLocation(javax.swing.JLabel venueLocation) {
        this.venueLocation = venueLocation;
    }

    /**
     * @return the venueName
     */
    public javax.swing.JLabel getVenueName() {
        return venueName;
    }

    /**
     * @param venueName the venueName to set
     */
    public void setVenueName(javax.swing.JLabel venueName) {
        this.venueName = venueName;
    }
    public void cancelBookingListener(ActionListener listener){
        
        this.cancelBooking.addActionListener(listener);
    }

    
    public void backListener(MouseListener listener)
    {
        this.backprofile.addMouseListener(listener);
    }

    /**
     * @return the price
     */
    public javax.swing.JLabel getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(javax.swing.JLabel price) {
        this.price = price;
    }
    
    




}
