/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Yuri Maharjan
 */
public class RegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationView
     */
    public RegistrationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passShowbtn = new javax.swing.JButton();
        confirmPassshowbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        passPsf = new javax.swing.JPasswordField();
        confirmPsf = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        alreadyLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirm Password:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel4.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 20));

        passShowbtn.setBackground(new java.awt.Color(0, 204, 51));
        passShowbtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        passShowbtn.setForeground(new java.awt.Color(255, 255, 255));
        passShowbtn.setText("Show");
        jPanel2.add(passShowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, 40));

        confirmPassshowbtn.setBackground(new java.awt.Color(0, 204, 0));
        confirmPassshowbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmPassshowbtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmPassshowbtn.setText("Show");
        jPanel2.add(confirmPassshowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, 40));

        jLabel3.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 60, 20));

        jLabel2.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 20));
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 320, 40));
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 320, 40));
        jPanel2.add(passPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 320, 40));
        jPanel2.add(confirmPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 320, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Register");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 320, 40));

        alreadyLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        alreadyLbl.setForeground(new java.awt.Color(0, 204, 51));
        alreadyLbl.setText("Already Have An Account?");
        jPanel2.add(alreadyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 560, 340));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("bookmyvenue");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 130, 40));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Register a new account!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 630, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyLbl;
    private javax.swing.JButton confirmPassshowbtn;
    private javax.swing.JPasswordField confirmPsf;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passPsf;
    private javax.swing.JButton passShowbtn;
    // End of variables declaration//GEN-END:variables

    
    public void RegisterUserListener(ActionListener listener)
    {
        this.jButton3.addActionListener(listener);
    }
    
    public void LoginNavigate(MouseListener listener)
    {
        this.alreadyLbl.addMouseListener(listener);
    }
    
    public void showPasswordListener(ActionListener listener)
    {
        this.getPassShowbtn().addActionListener(listener);
    }
    
    public void showConfirmPasswordListener(ActionListener listener)
    {
        this.getConfirmPassshowbtn().addActionListener(listener);
    }

    /**
     * @return the confirmPsf
     */
    public javax.swing.JPasswordField getConfirmPsf() {
        return confirmPsf;
    }

    /**
     * @param confirmPsf the confirmPsf to set
     */
    public void setConfirmPsf(javax.swing.JPasswordField confirmPsf) {
        this.confirmPsf = confirmPsf;
    }

    /**
     * @return the emailTxt
     */
    public javax.swing.JTextField getEmailTxt() {
        return emailTxt;
    }

    /**
     * @param emailTxt the emailTxt to set
     */
    public void setEmailTxt(javax.swing.JTextField emailTxt) {
        this.emailTxt = emailTxt;
    }

    /**
     * @return the nameTxt
     */
    public javax.swing.JTextField getNameTxt() {
        return nameTxt;
    }

    /**
     * @param nameTxt the nameTxt to set
     */
    public void setNameTxt(javax.swing.JTextField nameTxt) {
        this.nameTxt = nameTxt;
    }

    /**
     * @return the passPsf
     */
    public javax.swing.JPasswordField getPassPsf() {
        return passPsf;
    }

    /**
     * @param passPsf the passPsf to set
     */
    public void setPassPsf(javax.swing.JPasswordField passPsf) {
        this.passPsf = passPsf;
    }

    /**
     * @return the confirmPassshowbtn
     */
    public javax.swing.JButton getConfirmPassshowbtn() {
        return confirmPassshowbtn;
    }

    /**
     * @param confirmPassshowbtn the confirmPassshowbtn to set
     */
    public void setConfirmPassshowbtn(javax.swing.JButton confirmPassshowbtn) {
        this.confirmPassshowbtn = confirmPassshowbtn;
    }

    /**
     * @return the passShowbtn
     */
    public javax.swing.JButton getPassShowbtn() {
        return passShowbtn;
    }

    /**
     * @param passShowbtn the passShowbtn to set
     */
    public void setPassShowbtn(javax.swing.JButton passShowbtn) {
        this.passShowbtn = passShowbtn;
    }
    
    
    
    
 
    
    

}
