/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author suhritsatyal
 */
public class RegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationView
     */
    public RegistrationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        passPsf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmPsf = new javax.swing.JPasswordField();
        confirmPassshowbtn = new javax.swing.JButton();
        passShowbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        alreadyLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirm Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 324, -1, 46));

        jLabel2.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 60, 46));
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 334, -1));

        jLabel3.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 70, 30));
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 334, -1));
        jPanel1.add(passPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 334, -1));

        jLabel4.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 20));
        jPanel1.add(confirmPsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 334, -1));

        confirmPassshowbtn.setBackground(new java.awt.Color(0, 153, 153));
        confirmPassshowbtn.setText("Show");
        jPanel1.add(confirmPassshowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 338, -1, -1));

        passShowbtn.setBackground(new java.awt.Color(0, 153, 153));
        passShowbtn.setText("Show");
        jPanel1.add(passShowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 287, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Register");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 401, 158, -1));

        alreadyLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        alreadyLbl.setForeground(new java.awt.Color(255, 255, 102));
        alreadyLbl.setText("Already Have An Account?");
        jPanel1.add(alreadyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyLbl;
    private javax.swing.JButton confirmPassshowbtn;
    private javax.swing.JPasswordField confirmPsf;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passPsf;
    private javax.swing.JButton passShowbtn;
    // End of variables declaration//GEN-END:variables

    
    public void RegisterUserListener(ActionListener listener)
    {
        this.jButton3.addActionListener(listener);
    }
    
    public void LoginNavigate(MouseListener listener)
    {
        this.alreadyLbl.addMouseListener(listener);
    }
    
    public void showPasswordListener(ActionListener listener)
    {
        this.getPassShowbtn().addActionListener(listener);
    }
    
    public void showConfirmPasswordListener(ActionListener listener)
    {
        this.getConfirmPassshowbtn().addActionListener(listener);
    }

    /**
     * @return the confirmPsf
     */
    public javax.swing.JPasswordField getConfirmPsf() {
        return confirmPsf;
    }

    /**
     * @param confirmPsf the confirmPsf to set
     */
    public void setConfirmPsf(javax.swing.JPasswordField confirmPsf) {
        this.confirmPsf = confirmPsf;
    }

    /**
     * @return the emailTxt
     */
    public javax.swing.JTextField getEmailTxt() {
        return emailTxt;
    }

    /**
     * @param emailTxt the emailTxt to set
     */
    public void setEmailTxt(javax.swing.JTextField emailTxt) {
        this.emailTxt = emailTxt;
    }

    /**
     * @return the nameTxt
     */
    public javax.swing.JTextField getNameTxt() {
        return nameTxt;
    }

    /**
     * @param nameTxt the nameTxt to set
     */
    public void setNameTxt(javax.swing.JTextField nameTxt) {
        this.nameTxt = nameTxt;
    }

    /**
     * @return the passPsf
     */
    public javax.swing.JPasswordField getPassPsf() {
        return passPsf;
    }

    /**
     * @param passPsf the passPsf to set
     */
    public void setPassPsf(javax.swing.JPasswordField passPsf) {
        this.passPsf = passPsf;
    }

    /**
     * @return the confirmPassshowbtn
     */
    public javax.swing.JButton getConfirmPassshowbtn() {
        return confirmPassshowbtn;
    }

    /**
     * @param confirmPassshowbtn the confirmPassshowbtn to set
     */
    public void setConfirmPassshowbtn(javax.swing.JButton confirmPassshowbtn) {
        this.confirmPassshowbtn = confirmPassshowbtn;
    }

    /**
     * @return the passShowbtn
     */
    public javax.swing.JButton getPassShowbtn() {
        return passShowbtn;
    }

    /**
     * @param passShowbtn the passShowbtn to set
     */
    public void setPassShowbtn(javax.swing.JButton passShowbtn) {
        this.passShowbtn = passShowbtn;
    }
    
    
    
    
 
    
    

}
