/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6.view;

import java.awt.event.ActionListener;

/**
 *
 * @author ishan-college
 */
public class ReportView extends javax.swing.JFrame {

    /**
     * Creates new form ReportVieww
     */
    public ReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issuesTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        reportList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        reportBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 397));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        issuesTxt.setColumns(20);
        issuesTxt.setRows(5);
        jScrollPane1.setViewportView(issuesTxt);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 120, 260, 90);

        jLabel1.setText("Report a problem:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 30, 120, 17);

        reportList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Inquiry", "Report a bug", "Change account information", "Report a potential violation" }));
        reportList.setSelectedIndex(2);
        reportList.setToolTipText("");
        reportList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportListActionPerformed(evt);
            }
        });
        jPanel1.add(reportList);
        reportList.setBounds(200, 50, 250, 23);

        jLabel2.setText("Other Issues:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 90, 130, 17);

        reportBtn.setText("Report");
        jPanel1.add(reportBtn);
        reportBtn.setBounds(210, 240, 72, 23);

        cancelBtn.setText("Cancel");
        jPanel1.add(cancelBtn);
        cancelBtn.setBounds(350, 240, 78, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 570, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reportListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea issuesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reportBtn;
    private javax.swing.JComboBox<String> reportList;
    // End of variables declaration//GEN-END:variables
    
    public void ReportListener (ActionListener listener){
        this.reportBtn.addActionListener(listener);
    }
    
    public void CancelListener (ActionListener listener){
        this.cancelBtn.addActionListener(listener);
    }

    /**
     * @return the issuesTxt
     */
    public javax.swing.JTextArea getIssuesTxt() {
        return issuesTxt;
    }

    /**
     * @param issuesTxt the issuesTxt to set
     */
    public void setIssuesTxt(javax.swing.JTextArea issuesTxt) {
        this.issuesTxt = issuesTxt;
    }

    /**
     * @return the reportList
     */
    public javax.swing.JComboBox<String> getReportList() {
        return reportList;
    }

    /**
     * @param reportList the reportList to set
     */
    public void setReportList(javax.swing.JComboBox<String> reportList) {
        this.reportList = reportList;
    }
    
}

