package javaapplication6.view;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.JPanel;


/**
 *
 * @author Yuri Maharjan
 */
public class UpdateVenueDetailsView extends javax.swing.JFrame {
    private File selectedFile;

    /**
     * Creates new form RegistrationView
     */
    public UpdateVenueDetailsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numberTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        UploadImage = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        alreadyLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 60, 20));
        jPanel2.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 320, 40));

        update.setBackground(new java.awt.Color(185, 250, 46));
        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setBorderPainted(false);
        update.setOpaque(true);
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 320, 40));

        jLabel7.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Location :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 20));
        jPanel2.add(locationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 320, 40));

        jLabel8.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Email:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 20));
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 320, 40));

        jLabel10.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact Number:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 20));
        jPanel2.add(numberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 320, 40));

        jLabel11.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Price Per Plate :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 20));
        jPanel2.add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 320, 40));

        UploadImage.setBackground(new java.awt.Color(255, 51, 51));
        UploadImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UploadImage.setForeground(new java.awt.Color(255, 255, 255));
        UploadImage.setText("Upload Image");
        UploadImage.setBorderPainted(false);
        UploadImage.setOpaque(true);
        jPanel2.add(UploadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 320, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 560, 400));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(185, 250, 46));
        jLabel5.setText("bookmyvenue");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 140, 40));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Update Your Venue!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 160, -1));

        jPanel3.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6.Image/bookmyvenue.png"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 0, 110, 60);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 60));

        alreadyLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alreadyLbl.setForeground(new java.awt.Color(185, 250, 46));
        alreadyLbl.setText("Back to Admin Dashboard");
        alreadyLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(alreadyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateVenueDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateVenueDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateVenueDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateVenueDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateVenueDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UploadImage;
    private javax.swing.JLabel alreadyLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField numberTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the PriceTxt
     */
    public javax.swing.JTextField getPriceTxt() {
        return priceTxt;
    }

    /**
     * @param PriceTxt the PriceTxt to set
     */
    public void setPriceTxt(javax.swing.JTextField PriceTxt) {
        this.priceTxt = PriceTxt;
    }

    /**
     * @return the emailTxt
     */
    public javax.swing.JTextField getEmailTxt() {
        return emailTxt;
    }

    /**
     * @param emailTxt the emailTxt to set
     */
    public void setEmailTxt(javax.swing.JTextField emailTxt) {
        this.emailTxt = emailTxt;
    }

    /**
     * @return the locationTxt
     */
    public javax.swing.JTextField getLocationTxt() {
        return locationTxt;
    }

    /**
     * @param locationTxt the locationTxt to set
     */
    public void setLocationTxt(javax.swing.JTextField locationTxt) {
        this.locationTxt = locationTxt;
    }

    /**
     * @return the nameTxt
     */
    public javax.swing.JTextField getNameTxt() {
        return nametxt;
    }

    /**
     * @param nameTxt the nameTxt to set
     */
    public void setNameTxt(javax.swing.JTextField nameTxt) {
        this.nametxt = nameTxt;
    }

    /**
     * @return the numberTxt
     */
    public javax.swing.JTextField getNumberTxt() {
        return numberTxt;
    }

    /**
     * @param numberTxt the numberTxt to set
     */
    public void setNumberTxt(javax.swing.JTextField numberTxt) {
        this.numberTxt = numberTxt;
    }
    
    public JPanel getPanel() {
        return jPanel2;
    }

    
    public void UpdateListener(ActionListener listener)
    {
        this.update.addActionListener(listener);
    }
        
    public void addUploadImageListener(ActionListener listener) {
        this.UploadImage.addActionListener(listener);
    }

    /**
     * @return the selectedFile
     */
    public File getSelectedFile() {
        return selectedFile;
    }

    /**
     * @param selectedFile the selectedFile to set
     */
    public void setSelectedFile(File selectedFile) {
        this.selectedFile = selectedFile;
    }
    

}
